on:
  workflow_call: {}

name: "Build"

permissions:
  contents: read

jobs:
  escript:
    name: "EScript"

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Setup BEAM"
        uses: erlef/setup-beam@5304e04ea2b355f03681464e683d92e3b2f18451 # v1.18.2
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict

      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
        with:
          name: escript
          path: .

      - run: mix escript.install mix_dependency_submission --force
      - run: echo ~/.mix/escripts/ >> $GITHUB_PATH
      - run: mix_dependency_submission mix_dependency_submission
        env:
          GITHUB_TOKEN: ${{ github.token }}
